test:
	gcc -I src/lib/include src/lib/powers.c tests/powers.c -lcmocka -o out/powers
	gcc -I src/lib/include src/lib/patterns.c tests/patterns.c -lcmocka -o out/patterns
	gcc -ggdb -g3 -I src/lib/include src/lib/permutations.c tests/permutations.c -lcmocka -o out/permutations
