// Generated by CoffeeScript 1.7.1
(function() {
  var add, double, fact, fib, induction, induction_fact, induction_sum_int, induction_sum_sqr, mul, sumsqr, times;

  fib = function(n) {
    if (n < 2) {
      return n;
    } else {
      return (fib(n - 1)) + (fib(n - 2));
    }
  };

  fact = function(n) {
    if (n === 0) {
      return 1;
    } else {
      return n * fact(n - 1);
    }
  };

  times = function(n, m) {
    return n * m;
  };

  double = function(n) {
    return times(n, 2);
  };

  induction = function(base, comb, n) {
    if (n <= 0) {
      return base;
    } else {
      return comb(n(induction(base(comb(n - 1)))));
    }
  };

  add = function(x, y) {
    return x + y;
  };

  mul = function(x, y) {
    return x * y;
  };

  sumsqr = function(x, y) {
    return add(mul(x(x, y)));
  };

  induction_fact = function(n) {
    return induction(1, mul, n);
  };

  induction_sum_int = function(n) {
    return induction(0, add, n);
  };

  induction_sum_sqr = function(n) {
    return induction(0, sumsqr, n);
  };

  exports.fib = fib;

  exports.fact = fact;

  exports.times = times;

  exports.double = double;

  exports.induction = induction;

  exports.induction_fact = induction_fact;

  exports.induction_sum_int = induction_sum_int;

  exports.induction_sum_sqr = induction_sum_sqr;

}).call(this);
