all:
	cargo build

update:
	cargo update

test:
	cargo test

test-shift-cipher:
	cargo test shift_cipher
test-sub-cipher:
	cargo test substitution_cipher
test-affine-cipher:
	cargo test affine_cipher
