all:
	cargo build

update:
	cargo update

test:
	cargo test

test-shift-cipher:
	cargo test shift_cipher
test-sub-cipher:
	cargo test substitution_cipher
test-affine-cipher:
	cargo test affine_cipher
test-vigenere-cipher:
	cargo test vigenere_cipher
test-hill-cipher:
	cargo test hill_cipher
test-permutation-cipher:
	cargo test permutation_cipher

test-matrix:
	cargo test matrix
