all:
	pulp build --to dist/all.js

hello:
	./bin/build_main.sh all_hello.js Pure.Hello helloMain

ui_thermite_factorial:
	./bin/build_main.sh all_ui_thermite_factorial.js Pure.UI.Thermite.Factorial uiThermiteFactorialMain
